name = input ("Please enter your name:")
print ("\nWelcome to python, " + name +"!")
print("The type of the variable name is" , type(name))
age=input("\nEnter your age: ")
age= int (age)
print("\nYour age is",age)
print("The type of the variable age is", type(age))